# Generated by Django 3.0.5 on 2020-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep', '0002_string_new_para'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='String',
            new_name='Replacewords',
        ),
    ]
